// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteEventsByIdData, DeleteEventsByIdErrors, DeleteEventsByIdJoinData, DeleteEventsByIdJoinErrors, DeleteEventsByIdJoinResponses, DeleteEventsByIdResponses, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetEventsByIdData, GetEventsByIdErrors, GetEventsByIdResponses, GetEventsData, GetEventsErrors, GetEventsResponses, GetMeData, GetMeErrors, GetMeJoinedData, GetMeJoinedErrors, GetMeJoinedResponses, GetMeResponses, PatchEventsByIdData, PatchEventsByIdErrors, PatchEventsByIdResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRefreshData, PostAuthRefreshErrors, PostAuthRefreshResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostEventsByIdJoinData, PostEventsByIdJoinErrors, PostEventsByIdJoinResponses, PostEventsData, PostEventsErrors, PostEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>): RequestResult<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError> => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>): RequestResult<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

export const postAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRefreshData, ThrowOnError>): RequestResult<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthRefreshResponses, PostAuthRefreshErrors, ThrowOnError>({ url: '/auth/refresh', ...options });

export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Получение списка событий
 */
export const getEvents = <ThrowOnError extends boolean = false>(options?: Options<GetEventsData, ThrowOnError>): RequestResult<GetEventsResponses, GetEventsErrors, ThrowOnError> => (options?.client ?? client).get<GetEventsResponses, GetEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/',
    ...options
});

/**
 * Создание нового события
 */
export const postEvents = <ThrowOnError extends boolean = false>(options: Options<PostEventsData, ThrowOnError>): RequestResult<PostEventsResponses, PostEventsErrors, ThrowOnError> => (options.client ?? client).post<PostEventsResponses, PostEventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Удаление события
 */
export const deleteEventsById = <ThrowOnError extends boolean = false>(options: Options<DeleteEventsByIdData, ThrowOnError>): RequestResult<DeleteEventsByIdResponses, DeleteEventsByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteEventsByIdResponses, DeleteEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options
});

/**
 * Получение события по id
 */
export const getEventsById = <ThrowOnError extends boolean = false>(options: Options<GetEventsByIdData, ThrowOnError>): RequestResult<GetEventsByIdResponses, GetEventsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetEventsByIdResponses, GetEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options
});

/**
 * Обновление события
 */
export const patchEventsById = <ThrowOnError extends boolean = false>(options: Options<PatchEventsByIdData, ThrowOnError>): RequestResult<PatchEventsByIdResponses, PatchEventsByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchEventsByIdResponses, PatchEventsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Присоединение к событию
 */
export const deleteEventsByIdJoin = <ThrowOnError extends boolean = false>(options: Options<DeleteEventsByIdJoinData, ThrowOnError>): RequestResult<DeleteEventsByIdJoinResponses, DeleteEventsByIdJoinErrors, ThrowOnError> => (options.client ?? client).delete<DeleteEventsByIdJoinResponses, DeleteEventsByIdJoinErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}/join',
    ...options
});

/**
 * Присоединение к событию
 */
export const postEventsByIdJoin = <ThrowOnError extends boolean = false>(options: Options<PostEventsByIdJoinData, ThrowOnError>): RequestResult<PostEventsByIdJoinResponses, PostEventsByIdJoinErrors, ThrowOnError> => (options.client ?? client).post<PostEventsByIdJoinResponses, PostEventsByIdJoinErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events/{id}/join',
    ...options
});

/**
 * Получение списка моих событий
 */
export const getMeJoined = <ThrowOnError extends boolean = false>(options?: Options<GetMeJoinedData, ThrowOnError>): RequestResult<GetMeJoinedResponses, GetMeJoinedErrors, ThrowOnError> => (options?.client ?? client).get<GetMeJoinedResponses, GetMeJoinedErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/joined',
    ...options
});

/**
 * Получение списка моих событий
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/me/',
    ...options
});
