// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type PostAuthRegisterData = {
    body: {
        email: string;
        password: string;
        name: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    409: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    500: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Default Response
     */
    201: {
        accessToken: string;
        user: {
            id: string;
            email: string;
            name: string;
        };
    };
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        user: {
            id: string;
            email: string;
            name: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        email: string;
        name: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PostAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * Default Response
     */
    200: {
        accessToken: string;
        user: {
            id: string;
            email: string;
            name: string;
        };
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events/';
};

export type GetEventsErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetEventsError = GetEventsErrors[keyof GetEventsErrors];

export type GetEventsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        ownerId: string;
        joinedAt?: string | null;
    }>;
};

export type GetEventsResponse = GetEventsResponses[keyof GetEventsResponses];

export type PostEventsData = {
    body: {
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: unknown;
    };
    path?: never;
    query?: never;
    url: '/events/';
};

export type PostEventsErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostEventsError = PostEventsErrors[keyof PostEventsErrors];

export type PostEventsResponses = {
    /**
     * Default Response
     */
    200: {
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        ownerId: string;
        joinedAt?: string | null;
    };
};

export type PostEventsResponse = PostEventsResponses[keyof PostEventsResponses];

export type DeleteEventsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}';
};

export type DeleteEventsByIdErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    403: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    404: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type DeleteEventsByIdError = DeleteEventsByIdErrors[keyof DeleteEventsByIdErrors];

export type DeleteEventsByIdResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type GetEventsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}';
};

export type GetEventsByIdErrors = {
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    404: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetEventsByIdError = GetEventsByIdErrors[keyof GetEventsByIdErrors];

export type GetEventsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        ownerId: string;
        joinedAt?: string | null;
    };
};

export type GetEventsByIdResponse = GetEventsByIdResponses[keyof GetEventsByIdResponses];

export type PatchEventsByIdData = {
    body: {
        title?: string;
        description?: string;
        capacity?: number;
        address?: string;
        startsAt?: unknown;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}';
};

export type PatchEventsByIdErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    403: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    404: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PatchEventsByIdError = PatchEventsByIdErrors[keyof PatchEventsByIdErrors];

export type PatchEventsByIdResponses = {
    /**
     * Default Response
     */
    200: {
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        ownerId: string;
        joinedAt?: string | null;
    };
};

export type PatchEventsByIdResponse = PatchEventsByIdResponses[keyof PatchEventsByIdResponses];

export type DeleteEventsByIdJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/join';
};

export type DeleteEventsByIdJoinErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    404: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    409: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type DeleteEventsByIdJoinError = DeleteEventsByIdJoinErrors[keyof DeleteEventsByIdJoinErrors];

export type DeleteEventsByIdJoinResponses = {
    /**
     * Default Response
     */
    204: unknown;
};

export type PostEventsByIdJoinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/events/{id}/join';
};

export type PostEventsByIdJoinErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    404: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    409: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostEventsByIdJoinError = PostEventsByIdJoinErrors[keyof PostEventsByIdJoinErrors];

export type PostEventsByIdJoinResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        eventId: string;
        userId: string;
        joinedAt: string;
    };
};

export type PostEventsByIdJoinResponse = PostEventsByIdJoinResponses[keyof PostEventsByIdJoinResponses];

export type GetMeJoinedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/joined';
};

export type GetMeJoinedErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    500: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetMeJoinedError = GetMeJoinedErrors[keyof GetMeJoinedErrors];

export type GetMeJoinedResponses = {
    /**
     * Default Response
     */
    200: Array<{
        joinedAt: string;
        event: {
            title: string;
            description: string;
            capacity: number;
            address: string;
            startsAt: string;
            id: string;
            createdAt: string;
            updatedAt: string;
            ownerId: string;
            joinedAt?: string | null;
        };
    }>;
};

export type GetMeJoinedResponse = GetMeJoinedResponses[keyof GetMeJoinedResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/';
};

export type GetMeErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Default Response
     */
    200: Array<{
        title: string;
        description: string;
        capacity: number;
        address: string;
        startsAt: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        ownerId: string;
        joinedAt?: string | null;
    }>;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/';
};

export type GetUsersErrors = {
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        email: string;
        name: string;
        createdAt: string;
    }>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetMessagesConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/messages/conversations';
};

export type GetMessagesConversationsErrors = {
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetMessagesConversationsError = GetMessagesConversationsErrors[keyof GetMessagesConversationsErrors];

export type GetMessagesConversationsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        email: string;
        name: string;
        createdAt: string;
    }>;
};

export type GetMessagesConversationsResponse = GetMessagesConversationsResponses[keyof GetMessagesConversationsResponses];

export type GetMessagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type GetMessagesByIdErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type GetMessagesByIdError = GetMessagesByIdErrors[keyof GetMessagesByIdErrors];

export type GetMessagesByIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        senderId: string;
        receiverId: string;
        text: string | null;
        image: string | null;
        video: string | null;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetMessagesByIdResponse = GetMessagesByIdResponses[keyof GetMessagesByIdResponses];

export type PostMessagesByIdData = {
    body: {
        text: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/messages/{id}';
};

export type PostMessagesByIdErrors = {
    /**
     * Default Response
     */
    400: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
    /**
     * Default Response
     */
    401: {
        statusCode?: number;
        code?: string;
        error?: string;
        message: string;
    };
};

export type PostMessagesByIdError = PostMessagesByIdErrors[keyof PostMessagesByIdErrors];

export type PostMessagesByIdResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        senderId: string;
        receiverId: string;
        text: string | null;
        image: string | null;
        video: string | null;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostMessagesByIdResponse = PostMessagesByIdResponses[keyof PostMessagesByIdResponses];
