// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteEventsById, deleteEventsByIdJoin, getAuthMe, getEvents, getEventsById, getMe, getMeJoined, type Options, patchEventsById, postAuthLogin, postAuthLogout, postAuthRefresh, postAuthRegister, postEvents, postEventsByIdJoin } from '../sdk.gen';
import type { DeleteEventsByIdData, DeleteEventsByIdError, DeleteEventsByIdJoinData, DeleteEventsByIdJoinError, GetAuthMeData, GetAuthMeError, GetAuthMeResponse, GetEventsByIdData, GetEventsByIdError, GetEventsByIdResponse, GetEventsData, GetEventsError, GetEventsResponse, GetMeData, GetMeError, GetMeJoinedData, GetMeJoinedError, GetMeJoinedResponse, GetMeResponse, PatchEventsByIdData, PatchEventsByIdError, PatchEventsByIdResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthRefreshData, PostAuthRefreshError, PostAuthRefreshResponse, PostAuthRegisterData, PostAuthRegisterError, PostAuthRegisterResponse, PostEventsByIdJoinData, PostEventsByIdJoinError, PostEventsByIdJoinResponse, PostEventsData, PostEventsError, PostEventsResponse } from '../types.gen';

export const postAuthRegisterMutation = (options?: Partial<Options<PostAuthRegisterData>>): UseMutationOptions<PostAuthRegisterResponse, PostAuthRegisterError, Options<PostAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRegisterResponse, PostAuthRegisterError, Options<PostAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, GetAuthMeError, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

export const postAuthRefreshMutation = (options?: Partial<Options<PostAuthRefreshData>>): UseMutationOptions<PostAuthRefreshResponse, PostAuthRefreshError, Options<PostAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRefreshResponse, PostAuthRefreshError, Options<PostAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<unknown, DefaultError, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventsQueryKey = (options?: Options<GetEventsData>) => createQueryKey('getEvents', options);

/**
 * Получение списка событий
 */
export const getEventsOptions = (options?: Options<GetEventsData>) => queryOptions<GetEventsResponse, GetEventsError, GetEventsResponse, ReturnType<typeof getEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventsQueryKey(options)
});

/**
 * Создание нового события
 */
export const postEventsMutation = (options?: Partial<Options<PostEventsData>>): UseMutationOptions<PostEventsResponse, PostEventsError, Options<PostEventsData>> => {
    const mutationOptions: UseMutationOptions<PostEventsResponse, PostEventsError, Options<PostEventsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEvents({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Удаление события
 */
export const deleteEventsByIdMutation = (options?: Partial<Options<DeleteEventsByIdData>>): UseMutationOptions<unknown, DeleteEventsByIdError, Options<DeleteEventsByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteEventsByIdError, Options<DeleteEventsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEventsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getEventsByIdQueryKey = (options: Options<GetEventsByIdData>) => createQueryKey('getEventsById', options);

/**
 * Получение события по id
 */
export const getEventsByIdOptions = (options: Options<GetEventsByIdData>) => queryOptions<GetEventsByIdResponse, GetEventsByIdError, GetEventsByIdResponse, ReturnType<typeof getEventsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventsByIdQueryKey(options)
});

/**
 * Обновление события
 */
export const patchEventsByIdMutation = (options?: Partial<Options<PatchEventsByIdData>>): UseMutationOptions<PatchEventsByIdResponse, PatchEventsByIdError, Options<PatchEventsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchEventsByIdResponse, PatchEventsByIdError, Options<PatchEventsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchEventsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Присоединение к событию
 */
export const deleteEventsByIdJoinMutation = (options?: Partial<Options<DeleteEventsByIdJoinData>>): UseMutationOptions<unknown, DeleteEventsByIdJoinError, Options<DeleteEventsByIdJoinData>> => {
    const mutationOptions: UseMutationOptions<unknown, DeleteEventsByIdJoinError, Options<DeleteEventsByIdJoinData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteEventsByIdJoin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Присоединение к событию
 */
export const postEventsByIdJoinMutation = (options?: Partial<Options<PostEventsByIdJoinData>>): UseMutationOptions<PostEventsByIdJoinResponse, PostEventsByIdJoinError, Options<PostEventsByIdJoinData>> => {
    const mutationOptions: UseMutationOptions<PostEventsByIdJoinResponse, PostEventsByIdJoinError, Options<PostEventsByIdJoinData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postEventsByIdJoin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMeJoinedQueryKey = (options?: Options<GetMeJoinedData>) => createQueryKey('getMeJoined', options);

/**
 * Получение списка моих событий
 */
export const getMeJoinedOptions = (options?: Options<GetMeJoinedData>) => queryOptions<GetMeJoinedResponse, GetMeJoinedError, GetMeJoinedResponse, ReturnType<typeof getMeJoinedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMeJoined({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeJoinedQueryKey(options)
});

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Получение списка моих событий
 */
export const getMeOptions = (options?: Options<GetMeData>) => queryOptions<GetMeResponse, GetMeError, GetMeResponse, ReturnType<typeof getMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMeQueryKey(options)
});
